# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddbt < Formula
  desc "ddbt is a simple command line tool that does one job and one job only: delete all items in a AWS DynamoDB table."
  homepage "https://github.com/jenslauterbach/ddbt/"
  version "0.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/jenslauterbach/ddbt/releases/download/v0.1.0/ddbt_0.1.0_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
    sha256 "df0de9a049a4a79ff7b11db1689dce2da9a7a8a124c3df1aa78c9d7a7caf4da9"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/jenslauterbach/ddbt/releases/download/v0.1.0/ddbt_0.1.0_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
    sha256 "728459e3e6b9f731bf5620e0325df419b5190ddea4111f35e89d051711cb57ec"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jenslauterbach/ddbt/releases/download/v0.1.0/ddbt_0.1.0_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
    sha256 "88b293c949004eb492dea6fd81ba8fbad5a49934d254255909bc686e7ec64553"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jenslauterbach/ddbt/releases/download/v0.1.0/ddbt_0.1.0_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
    sha256 "de430a40a6ca46359cf32cc89d42d69456a2b704b6f4971983aad8c1f81fda54"
  end

  def install
    bin.install "ddbt"
  end

  test do
    system "#{bin}/ddbt --version"
  end
end
